# The "branches" section is for bors.
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build pull requests.
    - master

# adapted from https://tahoe-lafs.org/trac/tahoe-lafs/browser/trunk/.appveyor.yml
# adapted from https://packaging.python.org/en/latest/appveyor/
environment:
  matrix:
    # ASSUMPTION: It's pretty unlikely for Emanate to have failures on
    #             32-bit Python but not on 64-bit Python.
    #- PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    #- PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    #- PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

install:
  - |
    %PYTHON%\python.exe -m pip install -U pip
    %PYTHON%\python.exe -m pip install -U wheel virtualenv setuptools

# note:
# %PYTHON% has: python.exe
# %PYTHON%\Scripts has: pip.exe, tox.exe (and others installed by bare pip)

build: off
test_script:
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - |
    %PYTHON%\python.exe setup.py test
