Linux_task:
  container:
    matrix:
      - image: python:3.5-slim
      - image: python:3.6-slim
      - image: python:3.7-slim
  script:
    - python3 --version
    - python3 setup.py test

macOS_task:
  osx_instance:
    image: mojave-base
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
    matrix:
      - PYTHON: 3.6.8
      - PYTHON: 3.7.2
  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    - sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
    - brew install openssl readline pyenv
    - pyenv install ${PYTHON}
    - pyenv global ${PYTHON}
    - pyenv rehash
  script:
    - python3 --version
    - python3 setup.py test

FreeBSD_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    matrix:
      - PYTHON: 3.6
      - PYTHON: 3.7
  install_script: pkg install -y python`echo $PYTHON | tr -d '.'` py`echo $PYTHON | tr -d '.'`-setuptools
  script:
    - python${PYTHON} --version
    - python${PYTHON} setup.py test

Windows_task:
  windows_container:
    os_version: 2019
    matrix:
      - image: python:3.6-windowsservercore-1809
      - image: python:3.7-windowsservercore-1809

  script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe setup.py test
