# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# http://click.palletsprojects.com/en/5.x/python3/#python-3-surrogate-handling
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

Lint_task:
  container:
    image: python:3.8-slim
  install_script:
    - pip3 install -U .[testing]
  script:
    - pylint --version
    - bork run lint

Linux_task:
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-slim
  install_script:
    - pip3 install -U .[testing]
  script:
    - python3 --version
    - bork run test

macOS_task:
  osx_instance:
    image: mojave-base
  install_script:
    - brew install python3
    - pip3 install -U .[testing]
  script:
    - python3 --version
    - bork run test

FreeBSD_task:
  freebsd_instance:
    image_family: freebsd-12-1
  env:
    matrix:
      - PYTHON: 3.6
        # Python 3.6 on FreeBSD does not support the C.UTF-8 locale.
        LC_ALL: en_US.UTF-8
        LANG: en_US.UTF-8
      - PYTHON: 3.7
      - PYTHON: 3.8
  install_script:
    - PY=`echo $PYTHON | tr -d '.'`
    - pkg install -y python${PY} py${PY}-setuptools
    - python${PYTHON} -m ensurepip --upgrade
    - python${PYTHON} -m pip install -U 'pip>=19' # Hard requirement for no setup.py.
    - python${PYTHON} -m pip install .[testing_only]
  script:
    - python${PYTHON} --version
    - bork run test-only

Windows_task:
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  windows_container:
    os_version: 2019
    matrix:
      - image: python:3.6-windowsservercore-1809
      - image: python:3.7-windowsservercore-1809
      - image: python:3.8-windowsservercore-1809
  install_script:
    - C:\Python\python.exe -m pip install .[testing]
  script:
    - C:\Python\python.exe --version
    - bork run test
