Lint_task:
  container:
    image: python:3-slim
  install_script:
    - pip3 install -U .[test]
  script:
    - pylint --version
    - bork run lint

Linux_task:
  alias: Linux tests
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  container:
    matrix:
      - image: python:3.8-slim
      - image: python:3.9-slim
      - image: python:3.10-slim
      - image: python:3.11-slim
      - image: python:3.12-slim
  install_script:
    - pip3 install -U .[test]
  script:
    - python3 --version
    - pytest --verbose

macOS_task:
  alias: macOS tests
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-base:latest
  install_script:
    - brew install python3
    - pip3 install -U .[test]
  script:
    - python3 --version
    - pytest --verbose

FreeBSD_task:
  alias: FreeBSD tests
  freebsd_instance:
    image_family: freebsd-14-0
  env:
    matrix:
      - PYTHON: 3.8
      - PYTHON: 3.9
      - PYTHON: 3.10
      - PYTHON: 3.11
  install_script:
    - PY=`echo $PYTHON | tr -d '.'`
    - pkg install -y python${PY} py${PY}-setuptools
    - python${PYTHON} -m ensurepip --upgrade
    - python${PYTHON} -m pip install -U 'pip>=19' # Hard requirement for no setup.py.
    - python${PYTHON} -m pip install .[test]
  script:
    - python${PYTHON} --version
    - pytest --verbose

Windows_task:
  alias: Windows tests
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    matrix:
      - PYTHON: 3.8.18
      - PYTHON: 3.9.18
      - PYTHON: 3.10.9
      - PYTHON: 3.11.8
      - PYTHON: 3.12.2
  python_install_script:
    # https://docs.python.org/3.6/using/windows.html#installing-without-ui
    - ps: Invoke-WebRequest -Uri https://www.python.org/ftp/python/${env:PYTHON}/python-${env:PYTHON}-amd64.exe -OutFile C:\python-installer.exe
    - C:\python-installer.exe /quiet TargetDir=C:\Python SimpleInstall=1
  install_script:
    - C:\Python\python.exe -m pip install -U pip
    - C:\Python\python.exe -m pip install -e .[test]
  version_info_script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe -m pip --version
  test_script:
    - C:\Python\python.exe -m pytest --verbose


# Meta-task which depends on every other test/lint task to finish.
success_task:
  name: CI success
  container: {image: "busybox"}
  script: "exit 0"
  depends_on:
    - Lint
    - FreeBSD tests
    - Linux tests
    - macOS tests
    - Windows tests

# If the `version` file is modified on the main branch, make a release.
Release_task:
  only_if: "changesInclude('version') && $BRANCH == 'main' && $CIRRUS_CRON == ''"
  depends_on: [CI success]
  env:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: ENCRYPTED[93940c854f7cb146391fdb3ef75ab7f8e229e83837f49fbcb52472bcf3f1d0265ed8629fd57204152e019af4c6b9354c]
    BORK_GITHUB_TOKEN: ENCRYPTED[679e9111a081ade5978676e60c885be6d9fd08a1d37c73237686b575bd3a21892c8ca1dc29e99d6ed1e611915d7dc52b]
  container:
    image: python:3-slim
  install_script:
    - apt-get update
    - apt-get install -y git
    - pip3 install . .[test]
  build_script:
    - bork clean
    - bork build
  test_script:
    - bork run test
  release_script:
    - bork release
