# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# http://click.palletsprojects.com/en/5.x/python3/#python-3-surrogate-handling
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

Lint_task:
  container:
    image: python:3.8-slim
  install_script:
    - pip3 install -U bork .[testing]
  script:
    - flake8 --version
    - pylint --version
    - bork run lint

# Bork requires Twine, which requires Python>3.5.
# Remove Linux_Py35_task once Python 3.5 support is dropped.
Linux_Py35_task:
  container:
    image: python:3.5-slim
  install_script:
    - pip3 install -U .[testing]
  script:
    - python3 --version
    - pytest --pylint --flake8 --verbose


Linux_task:
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-slim
  install_script:
    - pip3 install -U bork .[testing]
  script:
    - python3 --version
    - bork run test

macOS_task:
  osx_instance:
    image: mojave-base
  env:
    PATH: ${HOME}/.pyenv/shims:${PATH}
  #  matrix:
  #    - PYTHON: 3.6.8
  #    - PYTHON: 3.7.5
  install_script:
    # Per the pyenv homebrew recommendations.
    # https://github.com/pyenv/pyenv/wiki#suggested-build-environment
    #- sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
    #- brew install openssl readline pyenv
    #- pyenv install ${PYTHON}
    #- pyenv global ${PYTHON}
    #- pyenv rehash
    - brew install python3
    - pip3 install -U bork .[testing]
  script:
    - python3 --version
    - bork run test

FreeBSD_task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  env:
    matrix:
      - PYTHON: 3.6
      - PYTHON: 3.7
  install_script:
    - PY=`echo $PYTHON | tr -d '.'`
    - pkg install -y python${PY} py${PY}-setuptools
    - python${PYTHON} -m ensurepip
    - python${PYTHON} -m pip install -U --upgrade-strategy eager pip setuptools wheel
    - python${PYTHON} -m pip install .[testing]
  script:
    - python${PYTHON} --version
    - python${PYTHON} -m pytest --verbose
    # FIXME: Convert FreeBSD to use the normal setup.

Windows_task:
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  windows_container:
    os_version: 2019
    matrix:
      - image: python:3.6-windowsservercore-1809
      - image: python:3.7-windowsservercore-1809
      - image: python:3.8-windowsservercore-1809
  install_script:
    - C:\Python\python.exe -m pip install -U --upgrade-strategy eager pip setuptools wheel
    - C:\Python\python.exe -m pip install .[testing]
  script:
    - C:\Python\python.exe --version
    - C:\Python\python.exe -m pytest --verbose
    # FIXME: Convert Windows to use the normal setup
