language: python
sudo: False

os:
  - linux
  - osx

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install: pip install tox-travis
script:  tox
env:
  - TOXENV=test


matrix:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=docstyle
    - os: linux
      python: 3.6
      env: TOXENV=flake8
    - os: linux
      python: 3.6
      env: TOXENV=lint
