language: python
sudo: False

# The "branches" section is for bors.
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build pull requests.
    - master

python:
  - "3.5"
  - "3.6"

cache:
  directories:
    # Caching .tox can spell trouble for checkers which save state. Technically,
    # pylint saves the previous build's score, but we don't use that value.
    - .tox
    - $HOME/.cache/pip

    # Cache the Homebrew downloads and the built Python versions
    - $HOME/Library/Caches/Homebrew
    - $HOME/.pyenv_cache

install: pip install tox
script:  tox
env:
  - TOXENV=test


matrix:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=docstyle
    - os: linux
      python: 3.6
      env: TOXENV=flake8
    - os: linux
      python: 3.6
      env: TOXENV=lint
      addons:
        apt:
          packages:
            - enchant

    # Dirty hacks to make OSX builds work on Travis
    # Inspired by https://pythonhosted.org/CodeChat/.travis.yml.html
    - os: osx
      language: generic
      env: TOXENV=test PYENV_VERSION=3.5.5 PATH="${HOME}/.pyenv/shims:${PATH}"
    - os: osx
      language: generic
      env: TOXENV=test PYENV_VERSION=3.6.5 PATH="${HOME}/.pyenv/shims:${PATH}"


before_install:
  # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || brew update'
  # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || brew upgrade openssl readline pyenv'
  # Remove everything unneeded from the brew cache
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || brew cleanup -s'
  # Install the desired python version
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || pyenv install $PYENV_VERSION'

  - python --version
  - pip    --version
