language: python
sudo: False

# The "branches" section is for bors.
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build pull requests.
    - master

#python:
#  - "3.5"
#  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

    # Cache the Homebrew downloads and the built Python versions
    - $HOME/Library/Caches/Homebrew
    - $HOME/.pyenv/cache
    - $HOME/.pyenv/versions

script: python setup.py test

matrix:
  include:
    - os: linux
      python: 3.5
      addons:
        apt:
          packages:
            - enchant

    - os: linux
      python: 3.6
      addons:
        apt:
          packages:
            - enchant

    # Dirty hacks to make OSX builds work on Travis
    # Inspired by https://pythonhosted.org/CodeChat/.travis.yml.html
    - os: osx
      language: generic
      env: TOXENV=test PYENV_VERSION=3.5.5 PATH="${HOME}/.pyenv/shims:${PATH}"
    - os: osx
      language: generic
      env: TOXENV=test PYENV_VERSION=3.6.5 PATH="${HOME}/.pyenv/shims:${PATH}"


before_install:
  # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || [ -d "$HOME/.pyenv/versions/$PYENV_VERSION" ] || brew update'
  # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || [ -d "$HOME/.pyenv/versions/$PYENV_VERSION" ] || brew upgrade openssl readline pyenv'
  # Remove everything unneeded from the brew cache.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || [ -d "$HOME/.pyenv/versions/$PYENV_VERSION" ] || brew cleanup -s'
  # Install the desired python version, if needed.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || [ -d "$HOME/.pyenv/versions/$PYENV_VERSION" ] || pyenv install $PYENV_VERSION'

  # Switch to the desired python version.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || pyenv global $PYENV_VERSION'
  # Generate appropriate shims.
  - '[ "$TRAVIS_OS_NAME" != "osx" ] || pyenv rehash'

  - python --version
  - pip    --version
