language: python
sudo: False

# The "branches" section is for bors.
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build pull requests.
    - master

python:
  - "3.5"
  - "3.6"

install: pip install tox-travis
script:  tox
env:
  - TOXENV=test


matrix:
  include:
    - os: linux
      python: 3.6
      env: TOXENV=docstyle
    - os: linux
      python: 3.6
      env: TOXENV=flake8
    - os: linux
      python: 3.6
      env: TOXENV=lint
      addons:
        apt:
          packages:
            - enchant

    # Dirty hacks to make OSX builds work on Travis
    # Inspired by https://pythonhosted.org/CodeChat/.travis.yml.html
    - os: osx
      language: generic
      env: TOXENV=test PYENV_VERSION=3.5.5 PATH="${HOME}/.pyenv/shims:${PATH}"
    - os: osx
      language: generic
      env: TOXENV=test PYENV_VERSION=3.6.5 PATH="${HOME}/.pyenv/shims:${PATH}"


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update
      # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
      brew upgrade openssl readline pyenv
      # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
      pyenv install $PYENV_VERSION
    fi

  - python --version
  - pip    --version
