status = [
  "FreeBSD LANG:en_US.UTF-8 LC_ALL:en_US.UTF-8 PYTHON:3.6",
  "FreeBSD LANG:C.UTF-8 LC_ALL:C.UTF-8 PYTHON:3.7",
  "FreeBSD LANG:C.UTF-8 LC_ALL:C.UTF-8 PYTHON:3.8",
  "Lint",
  "Linux container:python:3.6-slim",
  "Linux container:python:3.7-slim",
  "Linux container:python:3.8-slim",
  "Windows container:python:3.6-windowsservercore-1809",
  "Windows container:python:3.7-windowsservercore-1809",
  #"Windows container:python:3.8-windowsservercore-1809",
  "macOS",
]

delete_merged_branches = true
