status = [
  "FreeBSD PYTHON:3.6",
  "FreeBSD PYTHON:3.7",
  "Lint",
  "Linux container:python:3.5-slim",
  "Linux container:python:3.6-slim",
  "Linux container:python:3.7-slim",
  "Linux container:python:3.8-slim",
  "Windows container:python:3.6-windowsservercore-1809",
  "Windows container:python:3.7-windowsservercore-1809",
  "Windows container:python:3.8-windowsservercore-1809",
  "macOS",
]
